print("En este ejercicio se calculará y mostrará el perímetro de un rectángulo con los valores de base y altura")
b= float(input("Da la base "))
a= float(input("Da la altura "))
resultado = (a*2)+(b*2)
print(f"El perímetro de un rectángulo cuya base es {b} y altura es {a} es {resultado}")